SELECT * FROM usuario;
SELECT * FROM personagem;
SELECT * FROM atributo;
SELECT * FROM companheiro;
SELECT * FROM habilidadeBase;
SELECT * FROM habilidadeEspecializada;
SELECT * FROM personagem_has_habilidadeBase;
SELECT * FROM personagem_has_companheiro;
SELECT * FROM companheiro_has_habilidadeEspecializada;